/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/register': RouteRecordInfo<
      '/auth/register',
      '/auth/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blog/[id]': RouteRecordInfo<
      '/blog/[id]',
      '/blog/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/blog/edit/[id]': RouteRecordInfo<
      '/blog/edit/[id]',
      '/blog/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/blog/write': RouteRecordInfo<
      '/blog/write',
      '/blog/write',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dict/': RouteRecordInfo<
      '/dict/',
      '/dict',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hi/[name]': RouteRecordInfo<
      '/hi/[name]',
      '/hi/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/knowledge/chat': RouteRecordInfo<
      '/knowledge/chat',
      '/knowledge/chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/knowledge/daily': RouteRecordInfo<
      '/knowledge/daily',
      '/knowledge/daily',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/knowledge/sessions': RouteRecordInfo<
      '/knowledge/sessions',
      '/knowledge/sessions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project-blog': RouteRecordInfo<
      '/project-blog',
      '/project-blog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project-sweet-memory': RouteRecordInfo<
      '/project-sweet-memory',
      '/project-sweet-memory',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/README': RouteRecordInfo<
      '/README',
      '/README',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/about.vue': {
      routes:
        | '/about'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/register.vue': {
      routes:
        | '/auth/register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/blog/[id].vue': {
      routes:
        | '/blog/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/blog/edit/[id].vue': {
      routes:
        | '/blog/edit/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/blog/write.vue': {
      routes:
        | '/blog/write'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dict/index.vue': {
      routes:
        | '/dict/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/hi/[name].vue': {
      routes:
        | '/hi/[name]'
      views:
        | never
      pathParamNames:
        | 'name'
    }
    'src/pages/knowledge/chat.vue': {
      routes:
        | '/knowledge/chat'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/knowledge/daily.vue': {
      routes:
        | '/knowledge/daily'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/knowledge/sessions.vue': {
      routes:
        | '/knowledge/sessions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/project-blog.vue': {
      routes:
        | '/project-blog'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/project-sweet-memory.vue': {
      routes:
        | '/project-sweet-memory'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/README.md': {
      routes:
        | '/README'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
